version: "3.7"

services:
  scheduler:
    image: scheduler
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - CSV_REPOSITORY_FOLDER=/srv/data
    volumes:
      - ./data:/srv/data